session:
  prefix: x-token-dataplatform-
cookie:
  secret:
    hashKey: ed1805b0fa2b64ab199f0ad2c6f23eff8cfd4b31f6e690b66c7ce7e6f295817f
    blockKey: 7e845bb02d23f9ccb168e7935288e75ad97891023f509cccd9fb72868734bffc
oauth2:
  url:
    default: http://192.168.100.40:8601
  appid: dataplatform
  secret: de779fda524032d59ada70179b9f21d84000a269
  scopes:
    - dataplatform
web:
  routes:
  - path: /
    protected: true
    routeMode: local
    localRoute:
      index: index.html
      cache:
        option: no-cache
  - path: /js/sdk.js
    routeMode: local
    localRoute:
      path: js/sdk.js
      cache:
        option: no-cache


