export const ActionType = {
    // init
    STORE_INIT_QUESTION:'STORE_INIT_QUESTION',
    STORE_INIT_REQUESTBODY:'STORE_INIT_REQUESTBODY',
    STORE_INIT_RESPONSESTATE:'STORE_INIT_RESPONSESTATE',

    SET_LOCATION_SEARCH:'SET_LOCATION_SEARCH',
    USER_INFO_MODAL: 'USER_INFO_MODAL',
    USER_AGE_CHANGE:'USER_AGE_CHANGE',
    USER_TEL_CHANGE:'USER_TEL_CHANGE',
    USER_GENDER_CHANGE:'USER_GENDER_CHANGE',

    GLOBAL_LAODING_TOGGLE:'GLOBAL_LAODING_TOGGLE',

    // symptoms
    SYMPTOM_FETCH_PAGE_DATA:'SYMPTOM_FETCH_PAGE_DATA',
    SYMPTOM_FETCH_SEARCH_DATA:'SYMPTOM_FETCH_SEARCH_DATA',
    SYMPTOM_FETCH_SEARCH_TEXT:'SYMPTOM_FETCH_SEARCH_TEXT',
    SYMPTOM_FETCH_SELECTED:'SYMPTOM_FETCH_SELECTED',
    SYMPTOM_SEARCH_MASK_HIDE:'SYMPTOM_SEARCH_MASK_HIDE',
    SYMPTOM_SET_CURRENT_SORT:'SYMPTOM_SET_CURRENT_SORT',
    SYMPTOM_SET_SYMOTOM_CHOICE:'SYMPTOM_SET_SYMOTOM_CHOICE',
    SYMPTOM_SURE_SELECT:'SYMPTOM_SURE_SELECT',
    SYMPTOM_RECORD_ANSWER:'SYMPTOM_RECORD_ANSWER',

    //inquiry
    INQUIRY_FETCH_QUESTION:'INQUIRY_FETCH_QUESTION',
    INQUIRY_SHOWOPTIONS_TOGGLE:'INQUIRY_SHOWOPTIONS_TOGGLE',
    INQUIRY_SUBMIT_RESOULT:'INQUIRY_SUBMIT_RESOULT',
    INQUIRY_BACK_PREV:'INQUIRY_BACK_PREV',

    INQUIRY_RECORD_OPTIONS:'INQUIRY_RECORD_OPTIONS',
    INQUIRY_CLICK_WIDTHOUT:'INQUIRY_CLICK_WIDTHOUT',
    INQUIRY_RECORD_LAB_RESULT:'INQUIRY_RECORD_LAB_RESULT',
    INQUIRY_SURE_LAB:'INQUIRY_SURE_LAB',
    INQUIRY_CANCEL_LAB:'INQUIRY_CANCEL_LAB',

    WIKI_FETCH_DATA:'WIKI_FETCH_DATA',
    WIKI_ITEM_TOGGLE:'WIKI_ITEM_TOGGLE',
}