session:
  prefix: x-token-aidoctor-h5-
web:
  routes:
  - path: /
    protected: true
    routeMode: local
    localRoute:
      index: index.html
      cache:
        option: no-cache
  - path: /js/sdk.js
    routeMode: local
    localRoute:
      path: js/sdk.js
      cache:
        option: no-cache
  - path: /v2/
    protected: true
    routeMode: local
    localRoute:
      index: index.html
      path: v2/
      cache:
        option: no-cache
  - path: /v2/js/sdk.js
    routeMode: local
    localRoute:
      path: v2/js/sdk.js
      cache:
        option: no-cache
  - path: /pc/
    protected: true
    routeMode: local
    localRoute:
      index: index.html
      path: pc/
      cache:
        option: no-cache
  - path: /pc/js/sdk.js
    routeMode: local
    localRoute:
      path: pc/js/sdk.js
      cache:
        option: no-cache
